name: CI

on:
  push:
    branches: [ main, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm build
      - name: Unit tests
        run: |
          pnpm test || pnpm dlx vitest --run
      - name: E2E tests
        if: env.PREVIEW_URL != ''
        env:
          PREVIEW_URL: ${{ vars.PREVIEW_URL }}
        run: |
          pnpm test:e2e || pnpm dlx playwright test

